// <auto-generated />
namespace Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Version001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version001));
        
        string IMigrationMetadata.Id
        {
            get { return "201603251503558_Version-0.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
