// <auto-generated />
namespace IdentityServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AspNetIdentity001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AspNetIdentity001));
        
        string IMigrationMetadata.Id
        {
            get { return "201603251507363_AspNetIdentity-0.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
