//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApplication.PrivateAPI.IdentityServerUserManagement {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IdentityServerUserManagement.IWCFUserManagementService")]
    public interface IWCFUserManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFUserManagementService/Register", ReplyAction="http://tempuri.org/IWCFUserManagementService/RegisterResponse")]
        void Register(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFUserManagementService/Register", ReplyAction="http://tempuri.org/IWCFUserManagementService/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFUserManagementServiceChannel : MyApplication.PrivateAPI.IdentityServerUserManagement.IWCFUserManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFUserManagementServiceClient : System.ServiceModel.ClientBase<MyApplication.PrivateAPI.IdentityServerUserManagement.IWCFUserManagementService>, MyApplication.PrivateAPI.IdentityServerUserManagement.IWCFUserManagementService {
        
        public WCFUserManagementServiceClient() {
        }
        
        public WCFUserManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFUserManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFUserManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFUserManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Register(string userName, string password) {
            base.Channel.Register(userName, password);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(string userName, string password) {
            return base.Channel.RegisterAsync(userName, password);
        }
    }
}
